// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actors.sql

package database

import (
	"context"
)

const insertActor = `-- name: InsertActor :one
INSERT INTO actors(id, name, used)
VALUES (
  $1,
  $2,
  FALSE
)
RETURNING id, name, used
`

type InsertActorParams struct {
	ID   int32
	Name string
}

func (q *Queries) InsertActor(ctx context.Context, arg InsertActorParams) (Actor, error) {
	row := q.db.QueryRowContext(ctx, insertActor, arg.ID, arg.Name)
	var i Actor
	err := row.Scan(&i.ID, &i.Name, &i.Used)
	return i, err
}

const removeActor = `-- name: RemoveActor :exec
DELETE FROM actors
WHERE name = $1
`

func (q *Queries) RemoveActor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeActor, name)
	return err
}

const returnActors = `-- name: ReturnActors :many
SELECT id, name, used FROM actors
`

func (q *Queries) ReturnActors(ctx context.Context) ([]Actor, error) {
	rows, err := q.db.QueryContext(ctx, returnActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(&i.ID, &i.Name, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
