// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: films.sql

package database

import (
	"context"
)

const createFilm = `-- name: CreateFilm :exec
INSERT INTO films(id, title, poster_path)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (id) DO NOTHING
`

type CreateFilmParams struct {
	ID         int32
	Title      string
	PosterPath string
}

func (q *Queries) CreateFilm(ctx context.Context, arg CreateFilmParams) error {
	_, err := q.db.ExecContext(ctx, createFilm, arg.ID, arg.Title, arg.PosterPath)
	return err
}

const fetchPosters = `-- name: FetchPosters :one
SELECT poster_path FROM films
WHERE id = $1
`

func (q *Queries) FetchPosters(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, fetchPosters, id)
	var poster_path string
	err := row.Scan(&poster_path)
	return poster_path, err
}
