// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO game(date, created_at, actor_id, actor_name, film_1, film_2, film_3, film_1_id, film_2_id, film_3_id)
VALUES (
  $1,
  NOW(),
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING date, created_at, actor_id, actor_name, film_1, film_2, film_3, film_1_id, film_2_id, film_3_id
`

type CreateGameParams struct {
	Date      string
	ActorID   int32
	ActorName string
	Film1     string
	Film2     string
	Film3     string
	Film1ID   int32
	Film2ID   int32
	Film3ID   int32
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Date,
		arg.ActorID,
		arg.ActorName,
		arg.Film1,
		arg.Film2,
		arg.Film3,
		arg.Film1ID,
		arg.Film2ID,
		arg.Film3ID,
	)
	var i Game
	err := row.Scan(
		&i.Date,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorName,
		&i.Film1,
		&i.Film2,
		&i.Film3,
		&i.Film1ID,
		&i.Film2ID,
		&i.Film3ID,
	)
	return i, err
}

const returnGame = `-- name: ReturnGame :one
SELECT date, created_at, actor_id, actor_name, film_1, film_2, film_3, film_1_id, film_2_id, film_3_id FROM game
WHERE date = $1
`

func (q *Queries) ReturnGame(ctx context.Context, date string) (Game, error) {
	row := q.db.QueryRowContext(ctx, returnGame, date)
	var i Game
	err := row.Scan(
		&i.Date,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorName,
		&i.Film1,
		&i.Film2,
		&i.Film3,
		&i.Film1ID,
		&i.Film2ID,
		&i.Film3ID,
	)
	return i, err
}
