// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package database

import (
	"context"
	"time"
)

const createGame = `-- name: CreateGame :one
INSERT INTO game(date, actor_id)
VALUES (
  $1,
  $2
)
RETURNING date, actor_id
`

type CreateGameParams struct {
	Date    time.Time
	ActorID int32
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.Date, arg.ActorID)
	var i Game
	err := row.Scan(&i.Date, &i.ActorID)
	return i, err
}
