// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO game(date, created_at, actor_id, actor_name, film_1, film_2, film_3)
VALUES (
  $1,
  NOW(),
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING date, created_at, actor_id, actor_name, film_1, film_2, film_3
`

type CreateGameParams struct {
	Date      string
	ActorID   int32
	ActorName string
	Film1     string
	Film2     string
	Film3     string
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Date,
		arg.ActorID,
		arg.ActorName,
		arg.Film1,
		arg.Film2,
		arg.Film3,
	)
	var i Game
	err := row.Scan(
		&i.Date,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorName,
		&i.Film1,
		&i.Film2,
		&i.Film3,
	)
	return i, err
}

const returnGame = `-- name: ReturnGame :one
SELECT date, created_at, actor_id, actor_name, film_1, film_2, film_3 FROM game
WHERE date = $1
`

func (q *Queries) ReturnGame(ctx context.Context, date string) (Game, error) {
	row := q.db.QueryRowContext(ctx, returnGame, date)
	var i Game
	err := row.Scan(
		&i.Date,
		&i.CreatedAt,
		&i.ActorID,
		&i.ActorName,
		&i.Film1,
		&i.Film2,
		&i.Film3,
	)
	return i, err
}
