// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guesses.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGuess = `-- name: CreateGuess :one
INSERT INTO guesses(id, film_number, created_at, date, player_id, guess, verdict)
VALUES (
  gen_random_UUID(),
  $1,
  NOW(),
  $2,
  $3,
  $4,
  $5
)
RETURNING id, film_number, created_at, date, player_id, guess, verdict
`

type CreateGuessParams struct {
	FilmNumber int32
	Date       string
	PlayerID   uuid.UUID
	Guess      string
	Verdict    bool
}

func (q *Queries) CreateGuess(ctx context.Context, arg CreateGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, createGuess,
		arg.FilmNumber,
		arg.Date,
		arg.PlayerID,
		arg.Guess,
		arg.Verdict,
	)
	var i Guess
	err := row.Scan(
		&i.ID,
		&i.FilmNumber,
		&i.CreatedAt,
		&i.Date,
		&i.PlayerID,
		&i.Guess,
		&i.Verdict,
	)
	return i, err
}

const fetchGuess = `-- name: FetchGuess :one
SELECT id, film_number, created_at, date, player_id, guess, verdict FROM guesses
WHERE date = $1
AND player_id = $2
AND guess = $3
`

type FetchGuessParams struct {
	Date     string
	PlayerID uuid.UUID
	Guess    string
}

func (q *Queries) FetchGuess(ctx context.Context, arg FetchGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, fetchGuess, arg.Date, arg.PlayerID, arg.Guess)
	var i Guess
	err := row.Scan(
		&i.ID,
		&i.FilmNumber,
		&i.CreatedAt,
		&i.Date,
		&i.PlayerID,
		&i.Guess,
		&i.Verdict,
	)
	return i, err
}

const fetchGuessList = `-- name: FetchGuessList :many
SELECT id, film_number, created_at, date, player_id, guess, verdict FROM guesses
WHERE date = $1
AND player_id = $2
`

type FetchGuessListParams struct {
	Date     string
	PlayerID uuid.UUID
}

func (q *Queries) FetchGuessList(ctx context.Context, arg FetchGuessListParams) ([]Guess, error) {
	rows, err := q.db.QueryContext(ctx, fetchGuessList, arg.Date, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guess
	for rows.Next() {
		var i Guess
		if err := rows.Scan(
			&i.ID,
			&i.FilmNumber,
			&i.CreatedAt,
			&i.Date,
			&i.PlayerID,
			&i.Guess,
			&i.Verdict,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const strikeCount = `-- name: StrikeCount :one
SELECT COUNT(*) FROM guesses
WHERE date = $1
AND player_id = $2
AND verdict = FALSE
`

type StrikeCountParams struct {
	Date     string
	PlayerID uuid.UUID
}

func (q *Queries) StrikeCount(ctx context.Context, arg StrikeCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, strikeCount, arg.Date, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
