// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guesses.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGuess = `-- name: CreateGuess :one
INSERT INTO guesses(id, created_at, date, player_id, guess, verdict)
VALUES (
  gen_random_UUID(),
  NOW(),
  $1,
  $2,
  $3,
  $4
)
RETURNING id, created_at, date, player_id, guess, verdict
`

type CreateGuessParams struct {
	Date     string
	PlayerID uuid.UUID
	Guess    string
	Verdict  bool
}

func (q *Queries) CreateGuess(ctx context.Context, arg CreateGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, createGuess,
		arg.Date,
		arg.PlayerID,
		arg.Guess,
		arg.Verdict,
	)
	var i Guess
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Date,
		&i.PlayerID,
		&i.Guess,
		&i.Verdict,
	)
	return i, err
}

const fetchGuess = `-- name: FetchGuess :one
SELECT id, created_at, date, player_id, guess, verdict FROM guesses
WHERE date = $1
AND player_id = $2
AND guess = $3
`

type FetchGuessParams struct {
	Date     string
	PlayerID uuid.UUID
	Guess    string
}

func (q *Queries) FetchGuess(ctx context.Context, arg FetchGuessParams) (Guess, error) {
	row := q.db.QueryRowContext(ctx, fetchGuess, arg.Date, arg.PlayerID, arg.Guess)
	var i Guess
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Date,
		&i.PlayerID,
		&i.Guess,
		&i.Verdict,
	)
	return i, err
}

const strikeCount = `-- name: StrikeCount :one
SELECT COUNT(*) FROM guesses
WHERE date = $1
AND player_id = $2
AND verdict = FALSE
`

type StrikeCountParams struct {
	Date     string
	PlayerID uuid.UUID
}

func (q *Queries) StrikeCount(ctx context.Context, arg StrikeCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, strikeCount, arg.Date, arg.PlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
