// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Actor struct {
	ID   int32
	Name string
	Used bool
}

type Game struct {
	Date      string
	CreatedAt time.Time
	ActorID   int32
	ActorName string
	Film1     string
	Film2     string
	Film3     string
}

type Guess struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Date      string
	PlayerID  uuid.UUID
	Guess     string
	Verdict   bool
}
