// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Actor struct {
	ID   int32
	Name string
	Used bool
}

type Game struct {
	Date      string
	ActorID   int32
	ActorName string
	Film1     string
	Film2     string
	Film3     string
}

type Guess struct {
	ID       uuid.UUID
	Date     string
	PlayerID uuid.UUID
	Guess    string
	Verdict  bool
}
