// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Actor struct {
	ID   int32
	Name string
	Used bool
}

type Game struct {
	Date    time.Time
	ActorID int32
}
