// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_games.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserGame = `-- name: CreateUserGame :one
INSERT INTO user_games(id, created_at, date, player_id, actor, correct_guesses, incorrect_guesses, victory)
VALUES (
  gen_random_UUID(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, created_at, date, player_id, actor, correct_guesses, incorrect_guesses, victory
`

type CreateUserGameParams struct {
	Date             string
	PlayerID         uuid.UUID
	Actor            string
	CorrectGuesses   int32
	IncorrectGuesses int32
	Victory          bool
}

func (q *Queries) CreateUserGame(ctx context.Context, arg CreateUserGameParams) (UserGame, error) {
	row := q.db.QueryRowContext(ctx, createUserGame,
		arg.Date,
		arg.PlayerID,
		arg.Actor,
		arg.CorrectGuesses,
		arg.IncorrectGuesses,
		arg.Victory,
	)
	var i UserGame
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Date,
		&i.PlayerID,
		&i.Actor,
		&i.CorrectGuesses,
		&i.IncorrectGuesses,
		&i.Victory,
	)
	return i, err
}

const fetchStats = `-- name: FetchStats :one
SELECT COUNT(*) AS games_played,
COUNT(*) FILTER (WHERE victory = true AND incorrect_guesses = 0) AS perfect_wins,
COUNT(*) FILTER (WHERE victory = true) AS victories,
COUNT(*) FILTER (WHERE victory = false AND correct_guesses = 0) AS zero_correct,
COUNT(*) FILTER (WHERE victory = false AND correct_guesses = 1) AS one_correct,
COUNT(*) FILTER (WHERE victory = false AND correct_guesses = 2) AS two_correct
FROM user_games WHERE player_id = $1
`

type FetchStatsRow struct {
	GamesPlayed int64
	PerfectWins int64
	Victories   int64
	ZeroCorrect int64
	OneCorrect  int64
	TwoCorrect  int64
}

func (q *Queries) FetchStats(ctx context.Context, playerID uuid.UUID) (FetchStatsRow, error) {
	row := q.db.QueryRowContext(ctx, fetchStats, playerID)
	var i FetchStatsRow
	err := row.Scan(
		&i.GamesPlayed,
		&i.PerfectWins,
		&i.Victories,
		&i.ZeroCorrect,
		&i.OneCorrect,
		&i.TwoCorrect,
	)
	return i, err
}
